/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.robspassky.basic;


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.when;

@SpringBootTest
@ExtendWith(SpringExtension.class)
@SpringJUnitConfig
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class BarJobTest {

    private BarJob classUnderTest;

    Environment environment = Mockito.mock(Environment.class);

   CalculatorComponent calculatorComponent = Mockito.spy(CalculatorComponent.class);

    IncrementComponent incrementComponent = Mockito.spy(IncrementComponent.class);

    @BeforeEach
    public void setup() {
        when(environment.getRequiredProperty("samplejob.metadata.number")).thenReturn("42");
        classUnderTest = new BarJob(environment, calculatorComponent, incrementComponent);
    }

    @AfterEach
    public void teardown() {
        reset(environment);
        reset(incrementComponent);
    }


    @Test
    public void testCalcCurrentLine() {
        when(calculatorComponent.add(anyInt())).thenReturn(45);
        assertEquals(45, classUnderTest.calcCurrentLine());
    }

    @Test
    public void testDateToString() {
        Date d = new Date();
        d.setTime(3915000);
        assertEquals("20:05:15", classUnderTest.dateToString(d));
    }

    @Test
    public void testGetHomeDir() {
        when(environment.getRequiredProperty("user.home")).thenReturn("/dev/null");
        assertEquals("/dev/null", classUnderTest.getHomeDir());
    }

}
