/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.robspassky.basic;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int doAdd(int x, Calc c) {
        return c.add(x);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
