/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.robspassky.basic;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.env.Environment;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;

@SpringBootApplication
@EnableScheduling
public class Application {

    @Autowired
    private Environment environment;

    @Autowired
    private CalculatorComponent calculatorComponent;

    @Autowired
    private IncrementComponent incrementComponent;

    // run every 5s
    @Scheduled(fixedRate = 5000)
    public void runFooJob() {
        new FooJob(
                environment,
                incrementComponent
        ).run();
    }

    // For info on cron expressions in Spring Boot, see: https://www.baeldung.com/cron-expressions
    @Scheduled(cron = "3/10 * * * * ?")
    public void runBarJob() {
        new BarJob(
                environment,
                calculatorComponent,
                incrementComponent
        ).run();
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
